### ISSUE TITLE
`fst` broken

### ISSUE THREAD

**Issue by dvisztempacct** [GuillaumeSalles/resuggest#9]
Somehow, `fst` is allowed to be applied to a tuple with three elements, but the type of `fst` requires a 2-tuple input:

https://reasonml.github.io/en/try.html?rrjsx=true&reason=DYUwLgBAhhC8EAoCMBKA3AKFJARnRSANAEzpbgQDG+yJhAzGdhAB74BmAzmAlExQE8O3BDn6QAXsJ6V0QA

![bug](https://i.imgur.com/ctae82A.png)

**Comment by GuillaumeSalles** [comment]
Nice catch! Tuples with more than 2 elements were not handled properly. 

I fixed it in this commit : https://github.com/GuillaumeSalles/resuggest/commit/54930a9a1fef7bdf06ce106c62f886a8d326941a

Thanks a lot for the time you spent creating this issue, really appreciated.
